#!/usr/bin/env python3
# @file
#
# Component (iii)-part-3: standalone PoC packaging. Once a harness+input
# pair is confirmed (crashes pre-fix, doesn't post-fix, passes the LLM
# sanity check), this produces the actual final deliverable: a single,
# self-contained .c file that anyone can build and run directly, with the
# specific crash-triggering bytes baked in — no AFL++, no separate input
# file, no dependency on this pipeline. This is the direct structural
# equivalent of PoCGen's one-script exploit artifact (see Fig. 2 in the
# PoCGen paper): theirs fuses calling-code and crafted-data in one JS file
# because JS lets code and data share a syntax; ours achieves the same
# fusion in C by keeping the harness's existing functions untouched and
# supplying a custom main() with the winning bytes as a literal array,
# instead of ToolChainHarnessLib's normal argv[1]-file-reading main().
#
# The custom main() below is not a guess at what HBFAplus needs — it's a
# line-for-line mirror of the real sequence in
# HBFAplus/Infrastructure/ToolChainHarnessLib/ToolChainHarnessLib.c's own
# main(), with only the file-read (InitTestBuffer) step replaced by a
# direct assignment from the static array. Every function it calls
# (MockFuzzContextGetPool/Init/SetLimit/ClearLimit/AdvanceTo/Reset,
# MockTimerInit, MockEventResetState, MockEventSetAdvanceContext,
# ProcessLibraryConstructorList/DestructorList) is declared in
# FuzzContextLib.h or externed the same way the real file does — nothing
# invented.
#
# Copyright (c) 2025-2026 TianoShield Contributors.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
import dataclasses
import os
import re
import sys
from typing import Optional

STANDALONE_MAIN_TEMPLATE = """\
/** @file {base_name}.c
    Standalone, self-contained PoC for {ghsa_id} ({cve_id}) in {module}.

    This is the final reproduction artifact: {harness_c_filename}'s
    InitializeHarness/RunTestHarness/CleanupHarness/GetMaxBufferSize are
    reused UNCHANGED (see that file) — this module supplies only a custom
    main() that feeds them the exact bytes confirmed to trigger the crash,
    instead of ToolChainHarnessLib's normal argv[1]-file-reading main().

    Build and run this directly — no AFL++, no separate input file, no
    dependency on the AdvisoryPipeline that generated it:
        build -p HBFAplus/HBFAplus.dsc -m {base_name}.inf -a X64 -t GCC5
        ./Build/.../{base_name}

    Generated by AdvisoryPipeline's poc_packager.py from a confirmed
    crash-triggering input (validator.py verdict: confirmed).

    Copyright (c) 2026 TianoShield Contributors.
    SPDX-License-Identifier: BSD-2-Clause-Patent
**/

#include <stdlib.h>

#include <Uefi.h>
#include <Library/BaseLib.h>
#include <Library/FuzzContextLib.h>
#include <Library/DebugLib.h>

//
// Functions implemented, unchanged, by {harness_c_filename} — reused as-is.
//
extern VOID EFIAPI InitializeHarness (VOID);
extern VOID EFIAPI CleanupHarness (VOID);
extern VOID EFIAPI RunTestHarness (IN MOCK_FUZZ_CONTEXT *FuzzCtx);
extern UINTN EFIAPI GetMaxBufferSize (VOID);
extern UINTN EFIAPI __attribute__((weak)) GetBootstrapSize (VOID);

//
// Auto-generated by EDK2 build in AutoGen.c — same as ToolChainHarnessLib's
// real main() calls; rehosted-userspace substitute for the DXE dispatcher.
//
extern VOID EFIAPI ProcessLibraryConstructorList (VOID);
extern VOID EFIAPI ProcessLibraryDestructorList (VOID);

//
// Defined in UefiBootServicesTableLibHost/EventHost.c (already linked via
// this module's [LibraryClasses], same as the original harness).
//
extern VOID EFIAPI MockEventSetAdvanceContext (IN MOCK_FUZZ_CONTEXT *Ctx);
extern VOID EFIAPI MockTimerInit (VOID);
extern VOID EFIAPI MockEventResetState (VOID);

//
// The confirmed crash-triggering input — the actual proof-of-concept data.
// {reasoning}
//
STATIC CONST UINT8  mPocInput[] = {{
{byte_literal}
}};

STATIC MOCK_FUZZ_CONTEXT  *gFuzzCtx = NULL;

STATIC
VOID
CleanupWrapper (
  VOID
  )
{{
  CleanupHarness ();
  ProcessLibraryDestructorList ();
}}

int
main (
  int   argc,
  char  **argv
  )
{{
  UINTN  BootstrapSize;

  //
  // Load the hardcoded PoC bytes directly — this replaces
  // ToolChainHarnessLib's InitTestBuffer() (which reads argv[1] as a file).
  // Everything after this line is identical to the real main() sequence.
  //
  gFuzzCtx = MockFuzzContextGetPool ();
  MockFuzzContextInit (gFuzzCtx, (UINT8 *)mPocInput, sizeof (mPocInput));

  BootstrapSize = GetBootstrapSize ();
  if (BootstrapSize > 0) {{
    MockFuzzContextSetLimit (gFuzzCtx, BootstrapSize);
  }}

  MockTimerInit ();
  MockEventResetState ();
  MockEventSetAdvanceContext (gFuzzCtx);

  ProcessLibraryConstructorList ();

  InitializeHarness ();
  atexit (CleanupWrapper);

  if (BootstrapSize > 0) {{
    MockFuzzContextClearLimit (gFuzzCtx);
    MockFuzzContextAdvanceTo (gFuzzCtx, BootstrapSize);
  }}

  RunTestHarness (gFuzzCtx);
  MockFuzzContextReset (gFuzzCtx);

  return 0;
}}
"""

_LIBRARY_CLASSES_SECTION_RE = re.compile(
    r"(\[LibraryClasses\]\s*\n)((?:.*\n)*?)(\n?\[|\Z)", re.MULTILINE)
_SOURCES_SECTION_RE = re.compile(r"(\[Sources\]\s*\n)")
_BASE_NAME_RE = re.compile(r"^(\s*BASE_NAME\s*=\s*)(\S+)", re.MULTILINE)
_FILE_GUID_RE = re.compile(r"^(\s*FILE_GUID\s*=\s*)(\S+)", re.MULTILINE)


def render_byte_array(data: bytes, per_line: int = 12) -> str:
    """Render bytes as a C initializer list, e.g. '0x01, 0x00, ...',
    wrapped at `per_line` values per line for readability."""
    hex_values = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(hex_values), per_line):
        lines.append("  " + ", ".join(hex_values[i:i + per_line]) + ",")
    return "\n".join(lines) if lines else "  0x00,  // (empty input)"


def build_standalone_main_c(target: dict, advisory: dict,
                             harness_c_filename: str, base_name: str,
                             winning_bytes: bytes, reasoning: str = "") -> str:
    return STANDALONE_MAIN_TEMPLATE.format(
        base_name=base_name,
        ghsa_id=advisory.get("ghsa_id", "unknown"),
        cve_id=advisory.get("cve_id") or "no CVE assigned",
        module=target.get("module", "the target module"),
        harness_c_filename=harness_c_filename,
        reasoning=reasoning or "(no additional reasoning captured)",
        byte_literal=render_byte_array(winning_bytes),
    )


def derive_standalone_inf(original_inf_text: str, harness_c_filename: str,
                           standalone_c_filename: str, new_base_name: str) -> str:
    """Derive a new INF from the harness's own: same [Packages]/[Guids]/
    everything, [Sources] gets the new main() file added (the original
    harness .c stays, unchanged), and ToolChainHarnessLib is dropped from
    [LibraryClasses] since the new main() replaces the entry point it
    would have provided. Fresh BASE_NAME/FILE_GUID so it doesn't collide
    with the fuzzing-mode module in the same build.
    """
    text = original_inf_text

    # Add the new .c file to [Sources] (the original harness .c filename
    # should already be listed there from harness generation).
    text = _SOURCES_SECTION_RE.sub(
        lambda m: m.group(1) + f"  {standalone_c_filename}\n", text, count=1)

    # Drop ToolChainHarnessLib from [LibraryClasses] — anything else stays.
    def _strip_toolchain_lib(m):
        section_body = m.group(2)
        filtered = "\n".join(
            line for line in section_body.split("\n")
            if "ToolChainHarnessLib" not in line
        )
        return m.group(1) + filtered + m.group(3)

    text = _LIBRARY_CLASSES_SECTION_RE.sub(_strip_toolchain_lib, text, count=1)

    # Fresh BASE_NAME/FILE_GUID to avoid colliding with the original
    # fuzzing-mode module when both are built from the same workspace.
    text = _BASE_NAME_RE.sub(rf"\g<1>{new_base_name}", text, count=1)
    # A simple, deterministic-enough placeholder GUID derived from the
    # name — real uniqueness isn't security-critical here, just needs to
    # not collide with the original module's GUID in the same build.
    import hashlib
    guid_seed = hashlib.md5(new_base_name.encode()).hexdigest()
    fake_guid = (f"{guid_seed[0:8]}-{guid_seed[8:12]}-{guid_seed[12:16]}-"
                 f"{guid_seed[16:20]}-{guid_seed[20:32]}")
    text = _FILE_GUID_RE.sub(rf"\g<1>{fake_guid}", text, count=1)

    return text


def package_standalone_poc(attempt_dir: str, harness_inf_path: str,
                            harness_c_path: str, crash_input_path: str,
                            target: dict, advisory: dict,
                            reasoning: str = "",
                            try_build: bool = True,
                            workspace: Optional[str] = None) -> dict:
    """Orchestrates the whole packaging step. Best-effort and
    non-blocking: failures here never invalidate the underlying
    `confirmed` verdict, which already stands on its own from the
    harness+input pair validator.py already checked — this just produces
    a more convenient single-file version of the same proof.
    """
    harness_c_filename = os.path.basename(harness_c_path)
    original_base_name = os.path.splitext(harness_c_filename)[0]
    new_base_name = f"{original_base_name}StandalonePoC"
    standalone_c_filename = f"{new_base_name}.c"
    standalone_inf_filename = f"{new_base_name}.inf"

    with open(crash_input_path, "rb") as f:
        winning_bytes = f.read()

    standalone_c = build_standalone_main_c(
        target, advisory, harness_c_filename, new_base_name,
        winning_bytes, reasoning,
    )

    with open(harness_inf_path, "r") as f:
        original_inf_text = f.read()
    standalone_inf = derive_standalone_inf(
        original_inf_text, harness_c_filename, standalone_c_filename,
        new_base_name,
    )

    c_path = os.path.join(attempt_dir, standalone_c_filename)
    inf_path = os.path.join(attempt_dir, standalone_inf_filename)
    with open(c_path, "w") as f:
        f.write(standalone_c)
    with open(inf_path, "w") as f:
        f.write(standalone_inf)

    result = {
        "standalone_c_path": c_path,
        "standalone_inf_path": inf_path,
        "build_attempted": False,
        "build_ok": None,
        "build_log_tail": None,
    }

    if try_build and workspace:
        try:
            import validator
            inf_relpath = os.path.relpath(inf_path, workspace)
            build_result = validator.build_harness(inf_relpath, workspace)
            result["build_attempted"] = True
            result["build_ok"] = build_result.ok
            result["build_log_tail"] = build_result.log_tail[-2000:]
        except Exception as e:
            result["build_attempted"] = True
            result["build_ok"] = False
            result["build_log_tail"] = f"Build attempt raised: {e}"

    return result


def main():
    import argparse
    import json

    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--attempt-dir", required=True)
    parser.add_argument("--harness-inf", required=True)
    parser.add_argument("--harness-c", required=True)
    parser.add_argument("--crash-input", required=True)
    parser.add_argument("--target-json", required=True)
    parser.add_argument("--advisory-json", required=True)
    parser.add_argument("--reasoning", default="")
    parser.add_argument("--workspace")
    parser.add_argument("--no-build", action="store_true")
    args = parser.parse_args()

    with open(args.target_json) as f:
        target = json.load(f)
    with open(args.advisory_json) as f:
        advisory = json.load(f)

    result = package_standalone_poc(
        args.attempt_dir, args.harness_inf, args.harness_c, args.crash_input,
        target, advisory, args.reasoning, not args.no_build, args.workspace,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
